### ISSUE TITLE
Crie o left menu

### ISSUE THREAD

**Issue by Na1au** [TheBugMakers/agenda-medica#15]
Dentro do Admin template, teremos o componentedo menu lateral, que terá as rotas e o botão para logout, crie ele dentro da pasta components.
![image](https://user-images.githubusercontent.com/108345142/231759154-b1df96cf-dc0a-4c23-b864-ab3b7402a5dd.png)

**Comment by feliperobertosouz** [comment]
![image](https://user-images.githubusercontent.com/56833987/232038671-4ffe3f70-eaf3-441d-b018-1eb8e71bbd46.png)
Criado o leftmenu, ele é um componente, esta implementado no admintemplate na seção do codigo que havia comentarios para haver o leftmenu. Ele recebe um array de objetos com text, icone e rota. A propriedade se ele é visivel ou não é uma variavel dentro dele chamada drawer.

Se não faltar mais nada, só fechar a Issue 🤞
